// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: sentinel.proto

package sentinelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SentinelService_Validate_FullMethodName      = "/bastion.sentinel.v1.SentinelService/Validate"
	SentinelService_ValidateBatch_FullMethodName = "/bastion.sentinel.v1.SentinelService/ValidateBatch"
	SentinelService_Health_FullMethodName        = "/bastion.sentinel.v1.SentinelService/Health"
)

// SentinelServiceClient is the client API for SentinelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	ValidateBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type sentinelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelServiceClient(cc grpc.ClientConnInterface) SentinelServiceClient {
	return &sentinelServiceClient{cc}
}

func (c *sentinelServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, SentinelService_Validate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) ValidateBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, SentinelService_ValidateBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SentinelService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelServiceServer is the server API for SentinelService service.
// All implementations must embed UnimplementedSentinelServiceServer
// for forward compatibility
type SentinelServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	ValidateBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSentinelServiceServer()
}

// UnimplementedSentinelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSentinelServiceServer struct {
}

func (UnimplementedSentinelServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedSentinelServiceServer) ValidateBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBatch not implemented")
}
func (UnimplementedSentinelServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSentinelServiceServer) mustEmbedUnimplementedSentinelServiceServer() {}

// UnsafeSentinelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelServiceServer will
// result in compilation errors.
type UnsafeSentinelServiceServer interface {
	mustEmbedUnimplementedSentinelServiceServer()
}

func RegisterSentinelServiceServer(s grpc.ServiceRegistrar, srv SentinelServiceServer) {
	s.RegisterService(&SentinelService_ServiceDesc, srv)
}

func _SentinelService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_ValidateBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).ValidateBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_ValidateBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).ValidateBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentinelService_ServiceDesc is the grpc.ServiceDesc for SentinelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bastion.sentinel.v1.SentinelService",
	HandlerType: (*SentinelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _SentinelService_Validate_Handler,
		},
		{
			MethodName: "ValidateBatch",
			Handler:    _SentinelService_ValidateBatch_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SentinelService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentinel.proto",
}
